apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8080
      nodePort: 30080 # Открывает http://localhost:30080 или http://IP_MINIKUBE:30080
      protocol: TCP
      name: http
  selector:
    app: front
