apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8082
              name: http
          env:
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: SPRING_CLOUD_CONSUL_CONFIG_ENABLED
              value: "false"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED
              value: "false"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://bank-postgres:5432/account_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bank-global-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.postgresql.Driver"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "none" # Как в вашем файле properties
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              value: "true"
            - name: SPRING_SQL_INIT_MODE
              value: "always"

            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NOTIFICATION_CLIENT_PROVIDER
              value: "keycloak"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NOTIFICATION_CLIENT_AUTHORIZATION_GRANT_TYPE
              value: "client_credentials"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NOTIFICATION_CLIENT_CLIENT_ID
              value: "accounts-service-client"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NOTIFICATION_CLIENT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bank-global-secrets
                  key: ACCOUNTS_NOTIFICATION_CLIENT_SECRET

            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: "http://keycloak:8080/realms/bank-realm"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak:8080/realms/bank-realm"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak:8080/realms/bank-realm/protocol/openid-connect/certs"

            - name: APP_SERVICES_NOTIFICATION_URL
              value: "http://notification:8081"

            - name: RESILIENCE4J_CIRCUITBREAKER_INSTANCES_NOTIFICATIONS_SLIDING_WINDOW_SIZE
              value: "5"
            - name: RESILIENCE4J_CIRCUITBREAKER_INSTANCES_NOTIFICATIONS_FAILURE_RATE_THRESHOLD
              value: "50"
            - name: RESILIENCE4J_CIRCUITBREAKER_INSTANCES_NOTIFICATIONS_WAIT_DURATION_IN_OPEN_STATE
              value: "10s"
