spring.application.name=cash-service

app.consul.host=${CONSUL_HOST:localhost}
app.consul.port=${CONSUL_PORT:8500}

spring.config.import=optional:consul:${app.consul.host}:${app.consul.port}

spring.cloud.consul.host=${app.consul.host}
spring.cloud.consul.port=${app.consul.port}
spring.cloud.consul.discovery.instance-id=${spring.application.name}:docker

spring.cloud.consul.config.format=properties
spring.main.web-application-type=servlet

spring.cloud.consul.discovery.health-check-critical-timeout=10s

#server.port=8087
#
#spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/cash_db
#spring.datasource.username=postgres
#spring.datasource.password=root_password
#spring.jpa.hibernate.ddl-auto=validate
#
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://bank-keycloak:8080/realms/bank-realm
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/certs
#
#spring.security.oauth2.client.registration.cash-client.client-id=cash-service-client
#spring.security.oauth2.client.registration.cash-client.client-secret=iwrF4t35VCH5NeGz9U8N23GSdYqcWHSk
#spring.security.oauth2.client.registration.cash-client.client-authentication-method=client_secret_post
#spring.security.oauth2.client.registration.cash-client.authorization-grant-type=client_credentials
#spring.security.oauth2.client.registration.cash-client.provider=keycloak
#
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://bank-keycloak:8080/realms/bank-realm
#
#app.services.accounts-url=http://account-service
#app.services.notification-url=http://notification-service
#
#resilience4j.retry.instances.accounts.max-attempts=3
#resilience4j.retry.instances.accounts.wait-duration=1s
#
#resilience4j.retry.instances.accounts.retry-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException$BadGateway,org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable,org.springframework.web.reactive.function.client.WebClientResponseException$GatewayTimeout,io.netty.handler.timeout.ReadTimeoutException,java.net.ConnectException
#
#resilience4j.retry.instances.accounts.ignore-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest
#
#resilience4j.circuitbreaker.instances.accounts.sliding-window-size=5
#resilience4j.circuitbreaker.instances.accounts.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.accounts.wait-duration-in-open-state=10s
#
#resilience4j.circuitbreaker.instances.accounts.ignore-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest
#
#resilience4j.circuitbreaker.instances.notifications.sliding-window-size=5
#resilience4j.circuitbreaker.instances.notifications.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.notifications.wait-duration-in-open-state=10s
#
#resilience4j.circuitbreaker.instances.notifications.ignore-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest