apiVersion: v1
kind: Service
metadata:
  name: bank-postgres
  labels:
    app: bank-postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: bank-postgres
