spring.application.name=account-service

app.consul.host=${CONSUL_HOST:localhost}
app.consul.port=${CONSUL_PORT:8500}

spring.config.import=optional:consul:${app.consul.host}:${app.consul.port}

spring.cloud.consul.host=${app.consul.host}
spring.cloud.consul.port=${app.consul.port}
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}

spring.cloud.consul.config.format=properties
spring.cloud.consul.discovery.register-health-check=false
spring.main.web-application-type=servlet


#server.port=8082
#
#spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/account_db
#spring.datasource.username=postgres
#spring.datasource.password=root_password
#
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.sql.init.mode=always
#
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/bank-realm
#
## ????????? OAuth2 ??????? ??? Client Credentials Flow
#spring.security.oauth2.client.registration.notification-client.provider=keycloak
#spring.security.oauth2.client.registration.notification-client.authorization-grant-type=client_credentials
#spring.security.oauth2.client.registration.notification-client.client-id=accounts-service
#spring.security.oauth2.client.registration.notification-client.client-secret=BBufGQtj7zZQNswBvCPSuMS9BMjuxwBM
#
## ?????? ?? ????????? (Keycloak)
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/bank-realm
#
#
#app.services.notification-url=http://notification-service



