#spring.application.name=account-service
#
#app.consul.host=${CONSUL_HOST:localhost}
#app.consul.port=${CONSUL_PORT:8500}
#
#spring.config.import=optional:consul:${app.consul.host}:${app.consul.port}
#
#spring.cloud.consul.host=${app.consul.host}
#spring.cloud.consul.port=${app.consul.port}
#spring.cloud.consul.discovery.instance-id=${spring.application.name}:docker
#
#spring.cloud.consul.config.format=properties
##spring.cloud.consul.discovery.register-health-check=false
#spring.main.web-application-type=servlet
#
#spring.cloud.consul.discovery.health-check-critical-timeout=10s
#
#
#server.port=8082
#
#spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/account_db
#spring.datasource.username=postgres
#spring.datasource.password=root_password
#
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.sql.init.mode=always
#
#spring.security.oauth2.client.registration.notification-client.provider=keycloak
#spring.security.oauth2.client.registration.notification-client.authorization-grant-type=client_credentials
#spring.security.oauth2.client.registration.notification-client.client-id=accounts-service-client
#spring.security.oauth2.client.registration.notification-client.client-secret=NzQhQZt7JnPubsovCoVUbpIARuqgVIET
#
##spring.security.oauth2.client.provider.keycloak.issuer-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/bank-realm
#
##spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/bank-realm
##spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/bank-realm/protocol/openid-connect/certs
#
#
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://bank-keycloak:8080/realms/bank-realm
#
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://bank-keycloak:8080/realms/bank-realm
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/certs
#
#app.services.notification-url=http://notification-service
#
#resilience4j.circuitbreaker.instances.notifications.sliding-window-size=5
#resilience4j.circuitbreaker.instances.notifications.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.notifications.wait-duration-in-open-state=10s
#
#resilience4j.circuitbreaker.instances.notifications.ignore-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/account_db}
spring.datasource.username=postgres
spring.datasource.password=root_password

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
app.kafka.topics.notification=${APP_KAFKA_TOPICS_NOTIFICATION:bank-notifications}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/bank-realm}





