spring.application.name=account-service

app.consul.host=${CONSUL_HOST:localhost}
app.consul.port=${CONSUL_PORT:8500}

spring.config.import=optional:consul:${app.consul.host}:${app.consul.port}

spring.cloud.consul.host=${app.consul.host}
spring.cloud.consul.port=${app.consul.port}
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}

spring.cloud.consul.config.format=properties
#spring.cloud.consul.discovery.register-health-check=false
spring.main.web-application-type=servlet


#server.port=8082
#
#spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/account_db
#spring.datasource.username=postgres
#spring.datasource.password=root_password
#
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.sql.init.mode=always
#
#spring.security.oauth2.client.registration.notification-client.provider=keycloak
#spring.security.oauth2.client.registration.notification-client.authorization-grant-type=client_credentials
#spring.security.oauth2.client.registration.notification-client.client-id=accounts-service-client
#spring.security.oauth2.client.registration.notification-client.client-secret=Ey1RkyNB2kfeHtsjdBlAj6s5soVuT9cg
#
##spring.security.oauth2.client.provider.keycloak.issuer-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/bank-realm
#
##spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/bank-realm
##spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/bank-realm/protocol/openid-connect/certs
#
#
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://bank-keycloak:8080/realms/bank-realm
#
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://bank-keycloak:8080/realms/bank-realm
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/certs
#
#app.services.notification-url=http://notification-service



