#spring.application.name=my-bank-front-app
#
#app.consul.host=${CONSUL_HOST:localhost}
#app.consul.port=${CONSUL_PORT:8500}
#spring.config.import=optional:consul:${app.consul.host}:${app.consul.port}
#spring.cloud.consul.host=${app.consul.host}
#spring.cloud.consul.port=${app.consul.port}
#
#spring.cloud.consul.discovery.instance-id=${spring.application.name}:docker
##spring.cloud.consul.discovery.prefer-ip-address=true
#
#spring.cloud.consul.config.format=properties
##spring.cloud.consul.discovery.register-health-check=false
#
#spring.cloud.consul.discovery.health-check-critical-timeout=10s
#
#
server.port=${SERVER_PORT:8084}

spring.security.oauth2.client.registration.keycloak.user-name-attribute=preferred_username

spring.security.oauth2.client.registration.keycloak.client-id=${KEYCLOAK_CLIENT_ID:bank-ui}
spring.security.oauth2.client.registration.keycloak.client-secret=${FRONT_KEYCLOAK_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.provider.keycloak.authorization-uri=${KEYCLOAK_AUTHORIZATION_URI:http://localhost:8080/realms/bank-realm/protocol/openid-connect/auth}
spring.security.oauth2.client.provider.keycloak.token-uri=${KEYCLOAK_TOKEN_URI:http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/token}
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/certs}
spring.security.oauth2.client.provider.keycloak.user-info-uri=${KEYCLOAK_USER_INFO_URI:http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/userinfo}

#resilience4j.retry.instances.gateway.max-attempts=3
#resilience4j.retry.instances.gateway.wait-duration=1s
#
#resilience4j.retry.instances.gateway.retry-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException$BadGateway,org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable,org.springframework.web.reactive.function.client.WebClientResponseException$GatewayTimeout,java.net.ConnectException
#resilience4j.retry.instances.gateway.ignore-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest
#
#resilience4j.circuitbreaker.instances.gateway.sliding-window-size=5
#resilience4j.circuitbreaker.instances.gateway.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.gateway.wait-duration-in-open-state=10s
#resilience4j.circuitbreaker.instances.gateway.ignore-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest




#application
#spring.cloud.consul.discovery.register-health-check=false
#
#spring.cloud.config.fail-fast=true
#spring.cloud.consul.config.watch.delay=10000
#
#spring.cloud.consul.discovery.prefer-ip-address=true

app.services.gateway-url=${APP_SERVICES_GATEWAY_URL:http://localhost:8085}

