spring.application.name=my-bank-front-app

app.consul.host=${CONSUL_HOST:localhost}
app.consul.port=${CONSUL_PORT:8500}
spring.config.import=optional:consul:${app.consul.host}:${app.consul.port}
spring.cloud.consul.host=${app.consul.host}
spring.cloud.consul.port=${app.consul.port}

spring.cloud.consul.discovery.instance-id=${spring.application.name}
#spring.cloud.consul.discovery.prefer-ip-address=true

spring.cloud.consul.config.format=properties
#spring.cloud.consul.discovery.register-health-check=false


server.port=8084

#spring.security.oauth2.client.registration.keycloak.client-id=bank-ui
#spring.security.oauth2.client.registration.keycloak.client-secret=fXUEsKrWfHOK4pYh2rmgyYHFQ8qoo04F
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.scope=openid,profile
#spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.keycloak.provider=keycloak
#
#
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/bank-realm
#
#app.gateway.host=${GATEWAY_HOST:localhost}
#
#app.services.gateway-url=http://${app.gateway.host}:8085



#????????? application
#spring.cloud.consul.discovery.register-health-check=false
#
#spring.cloud.config.fail-fast=true
#spring.cloud.consul.config.watch.delay=10000
#
#spring.cloud.consul.discovery.prefer-ip-address=true

