#spring.application.name=my-bank-front-app
#
#app.consul.host=${CONSUL_HOST:localhost}
#app.consul.port=${CONSUL_PORT:8500}
#spring.config.import=optional:consul:${app.consul.host}:${app.consul.port}
#spring.cloud.consul.host=${app.consul.host}
#spring.cloud.consul.port=${app.consul.port}
#
#spring.cloud.consul.discovery.instance-id=${spring.application.name}:docker
##spring.cloud.consul.discovery.prefer-ip-address=true
#
#spring.cloud.consul.config.format=properties
##spring.cloud.consul.discovery.register-health-check=false
#
#spring.cloud.consul.discovery.health-check-critical-timeout=10s
#
#
#server.port=8084
#
#spring.security.oauth2.client.registration.keycloak.client-id=bank-ui
#spring.security.oauth2.client.registration.keycloak.client-secret=B8qFblHYQ20liM4QdS4getoKctNoj9tU
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.scope=openid,profile
#spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.keycloak.provider=keycloak
#
#
#
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://bank-keycloak:8080/realms/bank-realm
#spring.security.oauth2.client.provider.keycloak.authorization-uri=http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/auth
#spring.security.oauth2.client.provider.keycloak.token-uri=http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/token
#spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/certs
#app.gateway.host=${GATEWAY_HOST:localhost}
#
#app.services.gateway-url=http://${app.gateway.host}:8085
#
#resilience4j.retry.instances.gateway.max-attempts=3
#resilience4j.retry.instances.gateway.wait-duration=1s
#
#resilience4j.retry.instances.gateway.retry-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException$BadGateway,org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable,org.springframework.web.reactive.function.client.WebClientResponseException$GatewayTimeout,java.net.ConnectException
#resilience4j.retry.instances.gateway.ignore-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest
#
#resilience4j.circuitbreaker.instances.gateway.sliding-window-size=5
#resilience4j.circuitbreaker.instances.gateway.failure-rate-threshold=50
#resilience4j.circuitbreaker.instances.gateway.wait-duration-in-open-state=10s
#resilience4j.circuitbreaker.instances.gateway.ignore-exceptions=org.springframework.web.reactive.function.client.WebClientResponseException$BadRequest




#application
#spring.cloud.consul.discovery.register-health-check=false
#
#spring.cloud.config.fail-fast=true
#spring.cloud.consul.config.watch.delay=10000
#
#spring.cloud.consul.discovery.prefer-ip-address=true

app.services.gateway-url=${APP_SERVICES_GATEWAY_URL:http://localhost:8085}

