apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: SPRING_CLOUD_CONSUL_CONFIG_ENABLED
              value: "false"
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED
              value: "false"

            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak:8080/realms/bank-realm"

            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
              value: "account-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
              value: "http://accounts:8082" # Перевод на ClusterIP DNS
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
              value: "Path=/accounts/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0_NAME
              value: "TokenRelay"

            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
              value: "transfer-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
              value: "http://transfer:8083"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
              value: "Path=/transfers,/transfers/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0_NAME
              value: "TokenRelay"

            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
              value: "cash-service"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
              value: "http://cash:8087"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
              value: "Path=/cash,/cash/**"
            - name: SPRING_CLOUD_GATEWAY_ROUTES_2_FILTERS_0_NAME
              value: "TokenRelay"

            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY
              value: "TRACE"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: "DEBUG"
            - name: LOGGING_LEVEL_WEB
              value: "DEBUG"
