apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-global-config
data:
  KEYCLOAK_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "bank-realm"
  ACCOUNTS_URL: "http://accounts:8082"
  NOTIFICATION_URL: "http://notification:8086"
  TRANSFER_URL: "http://transfer:8086"
  CASH_URL: "http://cash:8083"

  RESILIENCE4J_RETRY_INSTANCES_ACCOUNTS_MAX_ATTEMPTS: "3"
  RESILIENCE4J_RETRY_INSTANCES_ACCOUNTS_WAIT_DURATION: "1s"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_ACCOUNTS_SLIDING_WINDOW_SIZE: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_ACCOUNTS_FAILURE_RATE_THRESHOLD: "50"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_ACCOUNTS_WAIT_DURATION_IN_OPEN_STATE: "10s"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_NOTIFICATIONS_SLIDING_WINDOW_SIZE: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_NOTIFICATIONS_FAILURE_RATE_THRESHOLD: "50"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_NOTIFICATIONS_WAIT_DURATION_IN_OPEN_STATE: "10s"
