apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kafka-config
  namespace: {{ .Release.Namespace }}
data:
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Release.Name }}-kafka:9092"

  KAFKA_PRODUCER_ACKS: "all"
  KAFKA_PRODUCER_RETRIES: "5"
  KAFKA_PRODUCER_RETRY_BACKOFF_MS: "100"
  KAFKA_PRODUCER_KEY_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
  KAFKA_PRODUCER_VALUE_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"

  KAFKA_CONSUMER_GROUP_ID: "notification-group-v3"
  KAFKA_CONSUMER_AUTO_OFFSET_RESET: "earliest"
  KAFKA_CONSUMER_ENABLE_AUTO_COMMIT: "false"
  KAFKA_CONSUMER_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  KAFKA_CONSUMER_VALUE_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
