apiVersion: v1
kind: Secret
metadata:
  name: bank-global-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: "cm9vdF9wYXNzd29yZA=="
  KEYCLOAK_CLIENT_SECRET: "TnpRaFFadDdKblB1YnNvdkNvVlVicElBUnVxZ1ZJRVQ="
