apiVersion: v1
kind: Secret
metadata:
  name: bank-global-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "root_password"
  TRANSFER_CLIENT_SECRET: "40MRsM2jMbHsOuA3QRsBZrTZZMtpOtuP"
  ACCOUNTS_NOTIFICATION_CLIENT_SECRET: "NzQhQZt7JnPubsovCoVUbpIARuqgVIET"
  FRONT_KEYCLOAK_CLIENT_SECRET: "B8qFblHYQ20liM4QdS4getoKctNoj9tU"
  CASH_KEYCLOAK_CLIENT_SECRET: "iwrF4t35VCH5NeGz9U8N23GSdYqcWHSk"
